name: xander9112
description: Сборник пакетов и библиотек для работы на проектах.
version: 0.0.5
homepage: https://github.com/xander9112/flutter_xander9112

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^8.2.0
  bloc: ^8.1.4
  collection: ^1.18.0
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  event_bus: ^2.0.0
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  package_info_plus: ^8.0.0
  reactive_forms: ^17.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter: null
