name: xander9112
description: Сборник пакетов и библиотек для работы на проектах.
version: 0.0.19
homepage: https://github.com/xander9112/flutter_xander9112

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  collection: ^1.18.0
  dartz: ^0.10.1
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  event_bus: ^2.0.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.2
  package_info_plus: ^8.1.1
  pretty_dio_logger: ^1.4.0
  reactive_forms: ^17.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
