name: xander9112
description: Сборник пакетов и библиотек для работы на проектах.
version: 0.0.1
homepage: https://github.com/xander9112/flutter_xander9112

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  collection: ^1.17.2
  dartz: ^0.10.1
  dio: ^5.3.3
  event_bus: ^2.0.0
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easy_dialogs: ^3.1.2
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  pretty_dio_logger: ^1.3.1
  reactive_forms: ^16.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
